export const ACCESO__MODULO_SEGURIDAD = 22;

export const ACCESO__PANEL_CONTROL_PRINCIPAL = 17;
export const ACCESO__PANEL_CONTROL_USUARIOS = 18;
export const ACCESO__PANEL_CONTROL_ROLES = 19;
export const ACCESO__PANEL_CONTROL_PERMISOS = 20;
export const ACCESO__PANEL_CONTROL_COMPONENTES = 21;

