import * as SEGURIDAD_ACTIONS from "@/constants/ACTIONS/SEGURIDAD_ACTIONS";

const actions = {
  COMPONENTE__SET_COMPONENTES: ({ commit }, payload) =>
    commit(SEGURIDAD_ACTIONS.COMPONENTE__SET_COMPONENTES, payload),
  COMPONENTE__UNSET_COMPONENTES: ({ commit }) => commit(SEGURIDAD_ACTIONS.COMPONENTE__UNSET_COMPONENTES),
  COMPONENTE__RESET: ({ commit }) => commit(SEGURIDAD_ACTIONS.COMPONENTE__RESET),
  COMPONENTE__ADD_COMPONENTE: ({ commit }, payload) =>
    commit(SEGURIDAD_ACTIONS.COMPONENTE__ADD_COMPONENTE, payload),
  COMPONENTE__UPDATE_COMPONENTE: ({ commit }, payload) =>
    commit(SEGURIDAD_ACTIONS.COMPONENTE__UPDATE_COMPONENTE, payload),
  COMPONENTE__SET_CURRENT_COMPONENTE: ({ commit }, payload) =>
    commit(SEGURIDAD_ACTIONS.COMPONENTE__SET_CURRENT_COMPONENTE, payload),
  COMPONENTE__UNSET_CURRENT_COMPONENTE: ({ commit }) => commit(SEGURIDAD_ACTIONS.COMPONENTE__UNSET_CURRENT_COMPONENTE),
};

export default actions;
