import * as SEGURIDAD_ACTIONS from "@/constants/ACTIONS/SEGURIDAD_ACTIONS";

const actions = {
  ESTADO_USUARIO__SET_ESTADOS_USUARIO: ({ commit }, payload) =>
    commit(SEGURIDAD_ACTIONS.ESTADO_USUARIO__SET_ESTADOS_USUARIO, payload),
  ESTADO_USUARIO__UNSET_ESTADOS_USUARIO: ({ commit }) => commit(SEGURIDAD_ACTIONS.ESTADO_USUARIO__UNSET_ESTADOS_USUARIO),
  ESTADO_USUARIO__RESET: ({ commit }) => commit(SEGURIDAD_ACTIONS.ESTADO_USUARIO__RESET),
};

export default actions;
