//#region ROL
export const ROL__SET_ROLES = 'ROL__SET_ROLES';
export const ROL__UNSET_ROLES = 'ROL__UNSET_ROLES';
export const ROL__ADD_ROL = 'ROL__ADD_ROL';
export const ROL__UPDATE_ROL = 'ROL__UPDATE_ROL';
export const ROL__SET_CURRENT_ROL = 'ROL__SET_CURRENT_ROL';
export const ROL__UNSET_CURRENT_ROL = 'ROL__UNSET_CURRENT_ROL';
export const ROL__RESET = 'ROL__RESET';
//#endregion ROL

//#region PERMISO
export const PERMISO__SET_PERMISOS = 'PERMISO__SET_PERMISOS';
export const PERMISO__UNSET_PERMISOS = 'PERMISO__UNSET_PERMISOS';
export const PERMISO__ADD_PERMISO = 'PERMISO__ADD_PERMISO';
export const PERMISO__UPDATE_PERMISO = 'PERMISO__UPDATE_PERMISO';
export const PERMISO__SET_CURRENT_PERMISO = 'PERMISO__SET_CURRENT_PERMISO';
export const PERMISO__UNSET_CURRENT_PERMISO = 'PERMISO__UNSET_CURRENT_PERMISO';
export const PERMISO__RESET = 'PERMISO__RESET';
//#endregion PERMISO

//#region USUARIO
export const USUARIO__SET_USUARIOS = 'USUARIO__SET_USUARIOS';
export const USUARIO__UNSET_USUARIOS = 'USUARIO__UNSET_USUARIOS';
export const USUARIO__ADD_USUARIO = 'USUARIO__ADD_USUARIO';
export const USUARIO__UPDATE_USUARIO = 'USUARIO__UPDATE_USUARIO';
export const USUARIO__UPDATE_USUARIO_ESTADO = 'USUARIO__UPDATE_USUARIO_ESTADO';
export const USUARIO__UPDATE_USUARIO_IMAGEN = 'USUARIO__UPDATE_USUARIO_IMAGEN';
export const USUARIO__DELETE_USUARIO_IMAGEN = 'USUARIO__DELETE_USUARIO_IMAGEN';
export const USUARIO__UPDATE_USUARIO_CLAVE_BY_CODIGO = 'USUARIO__UPDATE_USUARIO_CLAVE_BY_CODIGO';
export const USUARIO__UPDATE_USUARIO_CLAVE = 'USUARIO__UPDATE_USUARIO_CLAVE';
export const USUARIO__SET_CURRENT_USUARIO = 'USUARIO__SET_CURRENT_USUARIO';
export const USUARIO__UNSET_CURRENT_USUARIO = 'USUARIO__UNSET_CURRENT_USUARIO';
export const USUARIO__RESET = 'USUARIO__RESET';
export const USUARIO__LOGIN = 'USUARIO__LOGIN';
export const USUARIO__LOGOUT = 'USUARIO__LOGOUT';
export const USUARIO__REFRESH_TOKEN = 'USUARIO__REFRESH_TOKEN';
//#endregion USUARIO

//#region COMPONENTE
export const COMPONENTE__SET_COMPONENTES = 'COMPONENTE__SET_COMPONENTES';
export const COMPONENTE__UNSET_COMPONENTES = 'COMPONENTE__UNSET_COMPONENTES';
export const COMPONENTE__ADD_COMPONENTE = 'COMPONENTE__ADD_COMPONENTE';
export const COMPONENTE__UPDATE_COMPONENTE = 'COMPONENTE__UPDATE_COMPONENTE';
export const COMPONENTE__SET_CURRENT_COMPONENTE = 'COMPONENTE__SET_CURRENT_COMPONENTE';
export const COMPONENTE__UNSET_CURRENT_COMPONENTE = 'COMPONENTE__UNSET_CURRENT_COMPONENTE';
export const COMPONENTE__RESET = 'COMPONENTE__RESET';
//#endregion COMPONENTE

//#region ESTADO_USUARIO
export const ESTADO_USUARIO__SET_ESTADOS_USUARIO = 'ESTADO_USUARIO__SET_ESTADOS_USUARIO';
export const ESTADO_USUARIO__UNSET_ESTADOS_USUARIO = 'ESTADO_USUARIO__UNSET_ESTADOS_USUARIO';
export const ESTADO_USUARIO__RESET = 'ESTADO_USUARIO__RESET';
//#endregion ESTADO_USUARIO
